#!/usr/bin/env bash
#read and cut


while IFS=":" read -r USERNAME PASSWD USERID GROUPID INFO HOMEDIR CMDSH
do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIR and rides $CMDSH. $USERID's place is protected by the passcode $PASSWD, more info about the user here: $INFO"
done < /etc/passwd
