#!/usr/bin/env bash
#add bad luck and good luck


n=0
while [ $n -lt 10 ]
do
	if [ $n -eq 3 ]
	then
		echo "bad luck"
	elif [ $n -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$(( n+1 ))
done
